# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: check format for PRs on main affecting client folder

on:
  pull_request:
    branches: ["main"]
    paths:
      - "client/**"

jobs:
  client-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # let's save runners some work for now [18.x , 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: server/package-lock.json
      - name: npm install for ci
        run: npm ci
        working-directory: client
      - name: check formatting
        run: npm run format-check
        working-directory: client
    # TODO: remove comments to start checking the linting on the client
    # you can find the linting problems to be fixed with npm run lint-check
    # after fixing them uncomment the following lines

    #   - name: check linting
    #     run: npm run lint-check
    #     working-directory: client
